name: Deploy

on: 
 push:
  branches:
    - master
jobs:
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: mxschmitt/action-tmate@v3.17
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME }}
          key: ${{ secrets.KEY }}
          script: "cd /home/ubuntu/devops && ./deploy.sh"
